version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic-1:1:1"
    depends_on:
      - zookeeper
    links:
      - zookeeper

  kafdrop-ui:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - 8888:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      SERVER_SERVLET_CONTEXTPATH: "/"
